import type { Metadata } from 'next';
import Link from 'next/link';

export const metadata: Metadata = {
  title: 'Privacy Policy — Caller',
  description: 'Caller platform privacy policy. How we collect, use, and protect your data.',
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen" style={{ background: '#0e131f', color: '#dde2f3', fontFamily: 'Inter, system-ui, sans-serif' }}>
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@600;700;800&display=swap');
        .font-headline { font-family: 'Manrope', sans-serif; }
      `}</style>

      <header className="border-b" style={{ borderColor: 'rgba(255,255,255,0.04)' }}>
        <div className="max-w-4xl mx-auto px-6 py-5 flex items-center justify-between">
          <Link href="/" className="font-headline font-bold text-lg">Caller</Link>
          <div className="flex gap-4 text-xs" style={{ color: 'rgba(194,198,214,0.5)' }}>
            <Link href="/terms" className="hover:text-white transition-colors">Terms</Link>
            <Link href="/acceptable-use" className="hover:text-white transition-colors">Acceptable Use</Link>
          </div>
        </div>
      </header>

      <main className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="font-headline text-3xl font-bold mb-2">Privacy Policy</h1>
        <p className="text-sm mb-12" style={{ color: 'rgba(194,198,214,0.4)' }}>Last updated: April 9, 2026</p>

        <div className="space-y-10 text-sm leading-relaxed" style={{ color: 'rgba(194,198,214,0.7)' }}>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">1. Introduction</h2>
            <p>Caller (&quot;Company,&quot; &quot;we,&quot; &quot;us&quot;) respects your privacy and is committed to protecting the personal information you share with us. This Privacy Policy describes how we collect, use, disclose, and safeguard information when you use our AI phone calling platform (&quot;Service&quot;).</p>
            <p className="mt-2">This policy applies to all users of the Service, including business customers (&quot;Customers&quot;) and individuals who are called through the Service (&quot;Called Parties&quot;). If you are a California resident, please see Section 9 for your specific rights under the CCPA/CPRA.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">2. Information We Collect</h2>

            <h3 className="font-semibold text-white mt-4 mb-2">2.1 Information You Provide</h3>
            <ul className="list-disc list-inside space-y-1">
              <li><strong>Account Information:</strong> Name, email address, password (hashed), workspace name</li>
              <li><strong>Billing Information:</strong> Payment card details are processed by Stripe and never stored on our servers. We store Stripe customer IDs and transaction records.</li>
              <li><strong>Phone Numbers:</strong> Workspace phone numbers, called party numbers, caller IDs</li>
              <li><strong>Agent Configuration:</strong> AI agent names, system prompts, knowledge base documents, greetings</li>
              <li><strong>Provider Credentials:</strong> If you provide your own API keys (Twilio, Deepgram, etc.), they are encrypted at rest using AES-256-GCM</li>
            </ul>

            <h3 className="font-semibold text-white mt-4 mb-2">2.2 Information Generated Through Use</h3>
            <ul className="list-disc list-inside space-y-1">
              <li><strong>Call Recordings:</strong> Audio recordings of phone calls (when recording is enabled)</li>
              <li><strong>Transcripts:</strong> Text transcriptions of call audio generated by speech recognition services</li>
              <li><strong>AI Outputs:</strong> Summaries, sentiment analysis, action items, structured outcomes generated by AI models</li>
              <li><strong>Translation Data:</strong> Real-time translation text and audio for Live Translator sessions</li>
              <li><strong>Usage Data:</strong> Call duration, timestamps, costs, API usage metrics</li>
            </ul>

            <h3 className="font-semibold text-white mt-4 mb-2">2.3 Automatically Collected Information</h3>
            <ul className="list-disc list-inside space-y-1">
              <li><strong>Log Data:</strong> IP address, browser type, access times, pages viewed</li>
              <li><strong>Device Information:</strong> Operating system, device type</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">3. How We Use Your Information</h2>
            <ul className="list-disc list-inside space-y-1">
              <li><strong>Service Delivery:</strong> To make and receive phone calls, generate transcripts, provide AI agent services, and deliver live translation</li>
              <li><strong>Billing:</strong> To process payments, track usage costs, manage subscriptions</li>
              <li><strong>Security:</strong> To authenticate users, prevent fraud, detect unauthorized access</li>
              <li><strong>Improvement:</strong> To analyze aggregate usage patterns and improve the Service (we do not use your call recordings or transcripts for AI model training)</li>
              <li><strong>Communication:</strong> To send service-related notifications, billing alerts, and (with consent) product updates</li>
              <li><strong>Legal Compliance:</strong> To comply with applicable laws, regulations, and legal processes</li>
            </ul>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">4. Third-Party Service Providers</h2>
            <p>We share data with the following categories of service providers, solely to deliver the Service:</p>
            <div className="mt-3 overflow-x-auto">
              <table className="w-full text-xs" style={{ borderColor: 'rgba(255,255,255,0.08)' }}>
                <thead>
                  <tr style={{ borderBottom: '1px solid rgba(255,255,255,0.08)' }}>
                    <th className="text-left py-2 pr-4 text-white">Provider</th>
                    <th className="text-left py-2 pr-4 text-white">Purpose</th>
                    <th className="text-left py-2 text-white">Data Shared</th>
                  </tr>
                </thead>
                <tbody className="divide-y" style={{ borderColor: 'rgba(255,255,255,0.05)' }}>
                  <tr><td className="py-2 pr-4">Twilio</td><td className="py-2 pr-4">Telephony</td><td className="py-2">Phone numbers, call audio</td></tr>
                  <tr><td className="py-2 pr-4">Deepgram</td><td className="py-2 pr-4">Speech-to-text</td><td className="py-2">Call audio streams</td></tr>
                  <tr><td className="py-2 pr-4">OpenAI</td><td className="py-2 pr-4">AI models, speech recognition</td><td className="py-2">Text prompts, audio (API terms: not used for training)</td></tr>
                  <tr><td className="py-2 pr-4">Anthropic</td><td className="py-2 pr-4">AI models (Claude)</td><td className="py-2">Text prompts (API terms: not used for training)</td></tr>
                  <tr><td className="py-2 pr-4">ElevenLabs</td><td className="py-2 pr-4">Text-to-speech</td><td className="py-2">Text for voice synthesis</td></tr>
                  <tr><td className="py-2 pr-4">xAI</td><td className="py-2 pr-4">Voice agent (Grok)</td><td className="py-2">Audio streams for translation</td></tr>
                  <tr><td className="py-2 pr-4">Stripe</td><td className="py-2 pr-4">Payment processing</td><td className="py-2">Billing details (PCI DSS compliant)</td></tr>
                </tbody>
              </table>
            </div>
            <p className="mt-3">We maintain data processing agreements with all providers. We do not sell your personal information to third parties.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">5. Data Retention</h2>
            <ul className="list-disc list-inside space-y-1">
              <li><strong>Call Recordings:</strong> Retained per your workspace settings (default: 90 days). Configurable from 1 to 365 days.</li>
              <li><strong>Transcripts and Summaries:</strong> Retained for the life of your account unless deleted by you.</li>
              <li><strong>Account Data:</strong> Retained while your account is active and for 30 days after termination.</li>
              <li><strong>Billing Records:</strong> Retained for 7 years as required by tax and accounting regulations.</li>
              <li><strong>Audit Logs:</strong> Retained for 1 year for security purposes.</li>
            </ul>
            <p className="mt-2">You can delete specific recordings, transcripts, and call data at any time through the dashboard. Upon account termination, all Customer Data is deleted within 30 days, except billing records retained for legal compliance.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">6. Data Security</h2>
            <p>We implement industry-standard security measures to protect your data:</p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li>Encryption in transit (TLS 1.2+) and at rest (AES-256-GCM for sensitive credentials)</li>
              <li>API keys hashed with SHA-256 and verified using timing-safe comparison</li>
              <li>Workspace isolation — all data is scoped to individual workspaces</li>
              <li>Role-based access control (owner, admin, operator, analyst)</li>
              <li>Rate limiting on all API endpoints</li>
              <li>Audit logging for administrative actions</li>
            </ul>
            <p className="mt-2">No system is 100% secure. While we strive to protect your data, we cannot guarantee absolute security. You are responsible for securing your account credentials and API keys.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">7. Cookies and Tracking</h2>
            <p>We use essential cookies for authentication and session management. We do not use advertising cookies or third-party tracking pixels. We do not participate in cross-site tracking.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">8. Children&apos;s Privacy</h2>
            <p>The Service is not directed at individuals under 18 years of age. We do not knowingly collect personal information from children. If we learn that we have collected data from a child under 18, we will delete it promptly.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">9. California Privacy Rights (CCPA/CPRA)</h2>
            <p>If you are a California resident, you have the following rights under the California Consumer Privacy Act (CCPA) and the California Privacy Rights Act (CPRA):</p>
            <ul className="list-disc list-inside mt-2 space-y-1">
              <li><strong>Right to Know:</strong> You may request information about the categories and specific pieces of personal information we have collected about you, the sources, the business purposes, and the third parties with whom we share it.</li>
              <li><strong>Right to Delete:</strong> You may request deletion of your personal information, subject to certain exceptions (legal obligations, ongoing service delivery, security).</li>
              <li><strong>Right to Correct:</strong> You may request correction of inaccurate personal information.</li>
              <li><strong>Right to Opt-Out of Sale/Sharing:</strong> We do not sell or share your personal information for cross-context behavioral advertising. No opt-out is necessary, but you may contact us to confirm.</li>
              <li><strong>Right to Limit Use of Sensitive Personal Information:</strong> Voice recordings and precise call content are considered sensitive PI. We use this data only to provide the Service.</li>
              <li><strong>Non-Discrimination:</strong> We will not discriminate against you for exercising your privacy rights.</li>
            </ul>
            <p className="mt-2">To exercise any of these rights, contact us at <span className="text-blue-400">privacy@caller.com</span>. We will respond within 45 days. We may need to verify your identity before processing your request.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">10. International Data Transfers</h2>
            <p>The Service is hosted in the United States. If you access the Service from outside the US, you consent to the transfer of your data to the US, where data protection laws may differ from your jurisdiction.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">11. Changes to This Policy</h2>
            <p>We may update this Privacy Policy periodically. We will notify you of material changes by email or by posting a notice on the Service at least 30 days before the effective date. Your continued use of the Service constitutes acceptance of the updated policy.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-white mb-3">12. Contact Us</h2>
            <p>For privacy-related questions or to exercise your rights:</p>
            <p className="mt-2 text-white">Caller<br />Email: privacy@caller.com</p>
          </section>
        </div>
      </main>
    </div>
  );
}
