#!/usr/bin/env bash
set -euo pipefail

# =============================================================
# Caller - One-line installer
# Usage: curl -fsSL https://raw.githubusercontent.com/vskorokhod/caller/main/install.sh | bash
# Supports: Ubuntu 22.04+, Debian 11+
# =============================================================

REPO="https://github.com/sskorohod/caller.git"
INSTALL_DIR="$HOME/caller"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${CYAN}▶ $*${NC}"; }
success() { echo -e "${GREEN}✓ $*${NC}"; }
warn()    { echo -e "${YELLOW}⚠ $*${NC}"; }
error()   { echo -e "${RED}✗ $*${NC}" >&2; exit 1; }
prompt()  { echo -e "${BOLD}$*${NC}"; }

# ----- Header -----
echo ""
echo -e "${BOLD}╔══════════════════════════════════════╗${NC}"
echo -e "${BOLD}║       Caller AI Phone Agent          ║${NC}"
echo -e "${BOLD}║         Installer v0.1               ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════╝${NC}"
echo ""

# ----- Check OS -----
if [[ "$OSTYPE" != "linux-gnu"* ]]; then
  error "This installer supports Linux only. For macOS, see DEPLOY.md."
fi

# ----- Install Docker if missing -----
install_docker() {
  info "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
  sudo usermod -aG docker "$USER"
  success "Docker installed"
  warn "You may need to log out and back in for group changes to take effect."
  warn "If docker commands fail, run: newgrp docker"
}

if ! command -v docker &>/dev/null; then
  warn "Docker not found."
  read -r -p "Install Docker automatically? [Y/n] " yn
  [[ "${yn:-Y}" =~ ^[Yy]$ ]] && install_docker || error "Docker is required. Install it and re-run."
else
  success "Docker $(docker --version | awk '{print $3}' | tr -d ',')"
fi

if ! docker compose version &>/dev/null; then
  error "Docker Compose v2 is required. Update Docker to the latest version."
fi
success "Docker Compose $(docker compose version --short)"

# ----- Install git if missing -----
if ! command -v git &>/dev/null; then
  info "Installing git..."
  sudo apt-get update -qq && sudo apt-get install -y -qq git
  success "git installed"
fi

# ----- Clone or update repo -----
if [[ -d "$INSTALL_DIR/.git" ]]; then
  info "Updating existing installation at $INSTALL_DIR..."
  git -C "$INSTALL_DIR" pull --rebase
else
  info "Cloning Caller repository..."
  git clone "$REPO" "$INSTALL_DIR"
fi
cd "$INSTALL_DIR"

# ----- Generate secrets -----
gen_secret() {
  node -e "console.log(require('crypto').randomBytes(32).toString('hex'))" 2>/dev/null \
    || openssl rand -hex 32
}

gen_jwt_secret() {
  node -e "console.log(require('crypto').randomBytes(48).toString('base64url'))" 2>/dev/null \
    || openssl rand -base64 48 | tr -d '\n='
}

# ----- Interactive configuration -----
echo ""
prompt "═══ Configuration Wizard ══════════════════"
echo ""

# Domain
prompt "1. Your subdomain (e.g. caller.yourdomain.com):"
read -r -p "   Domain: " DOMAIN
[[ -z "$DOMAIN" ]] && error "Domain is required."

# PostgreSQL password
prompt "2. PostgreSQL password (leave blank to auto-generate):"
read -r -s -p "   Password: " POSTGRES_PASSWORD
echo ""
if [[ -z "$POSTGRES_PASSWORD" ]]; then
  POSTGRES_PASSWORD=$(gen_secret | head -c 32)
  warn "Auto-generated PostgreSQL password (saved in .env)"
fi

# Twilio
echo ""
prompt "3. Twilio credentials (get from twilio.com/console):"
read -r -p "   Twilio Auth Token (for webhook validation, can be set later): " TWILIO_WEBHOOK_SECRET
TWILIO_WEBHOOK_SECRET="${TWILIO_WEBHOOK_SECRET:-}"

# Optional providers
echo ""
prompt "4. Optional: Deepgram API key (for STT, can be configured later in dashboard):"
read -r -p "   Deepgram API key [skip]: " DEEPGRAM_KEY
DEEPGRAM_KEY="${DEEPGRAM_KEY:-}"

echo ""
prompt "5. Optional: ElevenLabs API key (for TTS, can be configured later in dashboard):"
read -r -p "   ElevenLabs API key [skip]: " ELEVENLABS_KEY
ELEVENLABS_KEY="${ELEVENLABS_KEY:-}"

# Auto-generate security secrets
info "Generating security keys..."
JWT_SECRET=$(gen_jwt_secret)
ENCRYPTION_KEY=$(gen_secret)

# ----- Write .env -----
info "Writing .env..."
cat > .env <<EOF
# Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M UTC")

DOMAIN=${DOMAIN}

POSTGRES_DB=caller
POSTGRES_USER=caller
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

TWILIO_WEBHOOK_SECRET=${TWILIO_WEBHOOK_SECRET}

LOG_LEVEL=info
NEXT_PUBLIC_API_URL=/api
EOF

success ".env written"

# ----- Configure nginx domain -----
info "Configuring nginx for domain: $DOMAIN"
sed -i "s/__DOMAIN__/${DOMAIN}/g" nginx/nginx.conf

# ----- Build and start -----
echo ""
info "Building Docker images (this takes 3-5 minutes on first run)..."
docker compose build --parallel

info "Starting services..."
docker compose up -d

# ----- Wait for backend health -----
echo ""
info "Waiting for backend to be ready..."
MAX_WAIT=120
ELAPSED=0
until docker compose exec -T backend wget -qO- http://localhost:3001/health >/dev/null 2>&1; do
  if [[ $ELAPSED -ge $MAX_WAIT ]]; then
    warn "Backend health check timed out. Check logs: docker compose logs backend"
    break
  fi
  echo -n "."
  sleep 3
  ELAPSED=$((ELAPSED + 3))
done
echo ""

# ----- Run database migrations -----
info "Running database migrations..."
docker compose exec -T backend node dist/migrate.js 2>/dev/null \
  || warn "Migration command not found — migrations may run automatically on startup."

# ----- Done -----
echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║            Installation Complete!            ║${NC}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Dashboard:${NC}  http://${DOMAIN}  (after CloudFlare DNS)"
echo -e "  ${BOLD}API:${NC}        http://${DOMAIN}/api/health"
echo ""
echo -e "${YELLOW}${BOLD}Next step — CloudFlare DNS:${NC}"
echo "  1. Go to CloudFlare Dashboard → DNS → Add record"
echo "  2. Type: A"
echo "  3. Name: $(echo "$DOMAIN" | cut -d. -f1)  (subdomain part)"
echo "  4. IPv4: $(curl -s ifconfig.me 2>/dev/null || echo '<YOUR_VPS_IP>')"
echo "  5. Proxy: Proxied (orange cloud)"
echo "  6. SSL/TLS mode: Full (in CloudFlare SSL/TLS settings)"
echo ""
echo -e "${YELLOW}${BOLD}Useful commands:${NC}"
echo "  docker compose logs -f          # view logs"
echo "  docker compose ps               # service status"
echo "  docker compose restart backend  # restart a service"
echo "  docker compose down             # stop everything"
echo "  docker compose pull && docker compose up -d  # update"
echo ""
echo -e "  Config file: ${BOLD}${INSTALL_DIR}/.env${NC}"
echo ""
