#!/usr/bin/env bash
set -euo pipefail

# =============================================================
# Caller - One-line installer
# Usage: curl -fsSL https://raw.githubusercontent.com/sskorohod/caller/main/install.sh | bash
# Supports: Ubuntu 22.04+, Debian 11+
# =============================================================

REPO="https://github.com/sskorohod/caller.git"
INSTALL_DIR="$HOME/caller"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info()    { echo -e "${CYAN}▶ $*${NC}"; }
success() { echo -e "${GREEN}✓ $*${NC}"; }
warn()    { echo -e "${YELLOW}⚠ $*${NC}"; }
error()   { echo -e "${RED}✗ $*${NC}" >&2; exit 1; }
prompt()  { echo -e "${BOLD}$*${NC}"; }

# Read user input from /dev/tty (works with curl | bash)
ask() {
  local varname="$1"
  local msg="$2"
  printf '%s' "$msg"
  IFS= read -r "$varname" </dev/tty
}

ask_secret() {
  local varname="$1"
  local msg="$2"
  printf '%s' "$msg"
  IFS= read -r -s "$varname" </dev/tty
  echo ""
}

ask_yn() {
  local varname="$1"
  local msg="$2"
  printf '%s' "$msg"
  IFS= read -r "$varname" </dev/tty
}

# ----- Header -----
echo ""
echo -e "${BOLD}╔══════════════════════════════════════╗${NC}"
echo -e "${BOLD}║       Caller AI Phone Agent          ║${NC}"
echo -e "${BOLD}║         Installer v0.3               ║${NC}"
echo -e "${BOLD}╚══════════════════════════════════════╝${NC}"
echo ""

# ----- Check Docker -----
if ! command -v docker &>/dev/null; then
  warn "Docker not found."
  ask_yn yn "Install Docker automatically? [Y/n] "
  if [[ "${yn:-Y}" =~ ^[Yy]$ ]]; then
    info "Installing Docker..."
    curl -fsSL https://get.docker.com | sh
    sudo usermod -aG docker "$USER" 2>/dev/null || true
    success "Docker installed"
    warn "If docker commands fail after install, run: newgrp docker"
  else
    error "Docker is required. Install it and re-run."
  fi
else
  success "Docker $(docker --version | awk '{print $3}' | tr -d ',')"
fi

if ! docker compose version &>/dev/null; then
  error "Docker Compose v2 is required. Update Docker to the latest version."
fi
success "Docker Compose $(docker compose version --short)"

# ----- Install git if missing -----
if ! command -v git &>/dev/null; then
  info "Installing git..."
  sudo apt-get update -qq && sudo apt-get install -y -qq git
  success "git installed"
fi

# ----- Clone or update repo -----
if [[ -d "$INSTALL_DIR/.git" ]]; then
  info "Updating existing installation at $INSTALL_DIR..."
  git -C "$INSTALL_DIR" pull --rebase
else
  info "Cloning Caller repository..."
  git clone "$REPO" "$INSTALL_DIR"
fi
cd "$INSTALL_DIR"

# ----- Interactive configuration -----
echo ""
echo -e "${BOLD}═══ Configuration Wizard ══════════════════${NC}"
echo ""

echo -e "${BOLD}1. Your subdomain (e.g. caller.yourdomain.com):${NC}"
ask DOMAIN "   Domain: "
[[ -z "$DOMAIN" ]] && error "Domain is required."

echo ""
echo -e "${BOLD}2. PostgreSQL password (Enter to auto-generate):${NC}"
ask_secret POSTGRES_PASSWORD "   Password: "
if [[ -z "$POSTGRES_PASSWORD" ]]; then
  POSTGRES_PASSWORD=$(openssl rand -base64 24 | tr -d '\n/+=')
  warn "Auto-generated password (saved in .env)"
fi

echo ""
echo -e "${BOLD}3. Twilio Auth Token (Enter to skip, set later in dashboard):${NC}"
ask TWILIO_WEBHOOK_SECRET "   Twilio Auth Token: "
TWILIO_WEBHOOK_SECRET="${TWILIO_WEBHOOK_SECRET:-}"

echo ""
echo -e "${BOLD}4. Deepgram API key for STT (Enter to skip):${NC}"
ask DEEPGRAM_KEY "   Deepgram API key: "
DEEPGRAM_KEY="${DEEPGRAM_KEY:-}"

echo ""
echo -e "${BOLD}5. ElevenLabs API key for TTS (Enter to skip):${NC}"
ask ELEVENLABS_KEY "   ElevenLabs API key: "
ELEVENLABS_KEY="${ELEVENLABS_KEY:-}"

# Auto-generate security secrets
info "Generating security keys..."
JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n/+=')
ENCRYPTION_KEY=$(openssl rand -hex 32)

# ----- Write .env -----
info "Writing .env..."
cat > .env <<EOF
# Generated by install.sh on $(date -u +"%Y-%m-%d %H:%M UTC")

DOMAIN=${DOMAIN}

POSTGRES_DB=caller
POSTGRES_USER=caller
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

JWT_SECRET=${JWT_SECRET}
ENCRYPTION_KEY=${ENCRYPTION_KEY}

TWILIO_WEBHOOK_SECRET=${TWILIO_WEBHOOK_SECRET}

LOG_LEVEL=info
NEXT_PUBLIC_API_URL=/api
EOF
success ".env written"

# ----- Configure nginx domain -----
info "Configuring nginx for domain: $DOMAIN"
sed -i "s/__DOMAIN__/${DOMAIN}/g" nginx/nginx.conf

# ----- Build and start -----
echo ""
info "Building Docker images (first run takes 3-5 min)..."
docker compose build --parallel

info "Starting services..."
docker compose up -d

# ----- Wait for backend health -----
echo ""
info "Waiting for backend to be ready..."
MAX_WAIT=120
ELAPSED=0
until docker compose exec -T backend wget -qO- http://localhost:3001/health >/dev/null 2>&1; do
  if [[ $ELAPSED -ge $MAX_WAIT ]]; then
    warn "Timed out waiting for backend."
    warn "Check logs: cd ~/caller && docker compose logs backend"
    break
  fi
  printf '.'
  sleep 3
  ELAPSED=$((ELAPSED + 3))
done
echo ""

# ----- Run database migrations -----
info "Running database migrations..."
if docker compose exec -T backend node dist/migrate.js; then
  success "Migrations complete"
else
  warn "Migration failed — check: docker compose logs backend"
fi

# ----- Done -----
echo ""
echo -e "${GREEN}${BOLD}╔══════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}${BOLD}║            Installation Complete!            ║${NC}"
echo -e "${GREEN}${BOLD}╚══════════════════════════════════════════════╝${NC}"
echo ""
echo -e "  ${BOLD}Dashboard:${NC}  https://${DOMAIN}"
echo -e "  ${BOLD}API:${NC}        https://${DOMAIN}/api/health"
echo ""
echo -e "${YELLOW}${BOLD}Useful commands (run from ~/caller):${NC}"
echo "  docker compose logs -f           # view logs"
echo "  docker compose logs backend      # backend only"
echo "  docker compose ps                # status"
echo "  docker compose restart backend   # restart service"
echo "  docker compose down              # stop all"
echo ""
echo -e "  Config: ${BOLD}${INSTALL_DIR}/.env${NC}"
echo ""
